### ISSUE TITLE
Selectively downsample datasets

### ISSUE THREAD

**Issue by SimoneMSR** [AlbinoDrought/chartjs-plugin-downsample#5]
Would be possible to use the plugin for downsampling a specific dataset?

**Comment by AlbinoDrought** [comment]
Merged https://github.com/AlbinoDrought/chartjs-plugin-downsample/pull/6 and https://github.com/AlbinoDrought/chartjs-plugin-downsample/pull/7 which added the option `targetDatasets`, published as 1.1.0.

https://albinodrought.github.io/chartjs-plugin-downsample/samples/target-datasets.html
