### ISSUE TITLE
Problem using Date x-axis

### ISSUE THREAD

**Issue by kmlbgn** [AlbinoDrought/chartjs-plugin-downsample#9]
Getting 

```
Uncaught TypeError: Cannot read property 'x' of undefined
    at downsample (chartjs-plugin-downsample.js:76)
```
I am using a date type x-axis and this line returns NaN 
`var pointAX = data[a].x * 1, // enforce Number (value may be Date)`

I tried using `new Date(data[a].x).getTime()` to force number but it doesn't work, `NextA` variable becomes 'undefined' and the code doesn't go further. 

What type of date object is compatible with your code ? 
thank you

**Comment by ilsaha** [comment]
@milkabe Hey, how did you fix this?

**Comment by kmlbgn** [comment]
Yo. Unfortunately I eventually stopped using chart js and got on Dygraph as it was less of a hassle in the end. 
I had a look at my old code to see where i left it , cause I think I had sorted this out.
This is what i have for the entire `for `loop: 

I've added a few `new Date()`

    for (var i = 0; i < threshold - 2; i++) {
        // Calculate point average for next bucket (containing c)
        var avgX = 0,
            avgY = 0,
            avgRangeStart = floor(( i + 1 ) * every) + 1,
            avgRangeEnd = floor(( i + 2 ) * every) + 1;
        avgRangeEnd = avgRangeEnd < dataLength ? avgRangeEnd : dataLength;

        var avgRangeLength = avgRangeEnd - avgRangeStart;

        for (; avgRangeStart < avgRangeEnd; avgRangeStart++) {
>            avgX += new Date(data[avgRangeStart].x) * 1; // * 1 enforces Number (value may be Date)
            avgY += data[avgRangeStart].y * 1;
        }
        avgX /= avgRangeLength;
        avgY /= avgRangeLength;

        // Get the range for this bucket
        var rangeOffs = floor((i + 0) * every) + 1,
            rangeTo = floor((i + 1) * every) + 1;

        // Point a
>        var pointAX = new Date(data[a].x) * 1, // enforce Number (value may be Date)
            pointAY = data[a].y * 1;

        maxArea = area = -1;

        for (; rangeOffs < rangeTo; rangeOffs++) {
            // Calculate triangle area over three buckets
            area = abs(( pointAX - avgX ) * ( data[rangeOffs].y - pointAY ) -
 >                   ( pointAX - new Date(data[rangeOffs].x) ) * ( avgY - pointAY )
                ) * 0.5;
            if (area > maxArea) {
                maxArea = area;
                maxAreaPoint = data[rangeOffs];
                nextA = rangeOffs; // Next a is this b
            }
        }

        sampled[sampledIndex++] = maxAreaPoint; // Pick this point from the bucket
        a = nextA; // This a is the next a (chosen b)
    }

**Comment by milkabe** [comment]
updated
